apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: villagers.village.example.com
spec:
  group: village.example.com
  names:
    kind: Villager
    plural: villagers
    singular: villager
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                name:
                  type: string
                status:
                  type: string
                  enum:
                    - idle
                    - talking
                target:
                  type: string
                  description: "The name of the villager to talk to"
                memory:
                  type: object
                  description: "The long-term memory of the villager, can include information like past conversations or events."
                  properties:
                    conversations:
                      type: array
                      items:
                        type: string
                      description: "A list of topics or messages the villager has discussed before."
                    preferences:
                      type: object
                      description: "The villager's preferences based on past experiences."
                      properties:
                        preferred_topics:
                          type: array
                          items:
                            type: string
                          description: "Topics the villager prefers to discuss."
                        disliked_topics:
                          type: array
                          items:
                            type: string
                          description: "Topics the villager dislikes discussing."
                personality:
                  type: object
                  description: "The villager's personality traits."
                  properties:
                    extroversion:
                      type: number
                      minimum: 0
                      maximum: 1
                      description: "A score between 0 and 1 indicating how extroverted the villager is."
                    agreeableness:
                      type: number
                      minimum: 0
                      maximum: 1
                      description: "A score between 0 and 1 indicating how agreeable the villager is."
                    openness:
                      type: number
                      minimum: 0
                      maximum: 1
                      description: "A score between 0 and 1 indicating how open the villager is to new ideas."
                    neuroticism:
                      type: number
                      minimum: 0
                      maximum: 1
                      description: "A score between 0 and 1 indicating how emotionally stable the villager is."
