# villager CRD
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: villagers.village.example.com
spec:
  group: village.example.com
  names:
    kind: Villager
    plural: villagers
    singular: villager
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                name:
                  type: string
                status:
                  type: string
                  enum:
                    - idle
                    - talking
                target:
                  type: string
                  description: "The name of the villager to talk to"
